/**
 * POLI Universal Export Utility
 * Supports 14 export formats: PDF, TXT, HTML, Markdown, JSON, XML, CSV, RTF, DOC, YAML, LaTeX, EPUB, ODF, TSV
 */

export interface ExportSection {
    heading: string;
    content: string | string[] | Record<string, any>;
}

export interface ExportData {
    title: string;
    type: string;
    subtitle?: string;
    sections?: ExportSection[];
    rawData?: Record<string, any>;
    date?: string;
}

export type ExportFormat =
    | 'pdf' | 'txt' | 'html' | 'md' | 'json' | 'xml'
    | 'csv' | 'rtf' | 'doc' | 'yaml' | 'tex' | 'epub'
    | 'odt' | 'tsv';

export const EXPORT_FORMATS: { id: ExportFormat; label: string; icon: string; ext: string; mime: string }[] = [
    { id: 'pdf',  label: 'PDF Document',    icon: 'PDF', ext: '.pdf',  mime: 'application/pdf' },
    { id: 'txt',  label: 'Plain Text',       icon: 'TXT', ext: '.txt',  mime: 'text/plain' },
    { id: 'html', label: 'HTML Page',        icon: 'HTM', ext: '.html', mime: 'text/html' },
    { id: 'md',   label: 'Markdown',         icon: '#',  ext: '.md',   mime: 'text/markdown' },
    { id: 'json', label: 'JSON Data',        icon: '{}', ext: '.json', mime: 'application/json' },
    { id: 'xml',  label: 'XML Document',     icon: 'XML', ext: '.xml',  mime: 'application/xml' },
    { id: 'doc',  label: 'Word Document',    icon: 'W',  ext: '.doc',  mime: 'application/msword' },
    { id: 'rtf',  label: 'Rich Text (RTF)',  icon: 'R',  ext: '.rtf',  mime: 'application/rtf' },
    { id: 'csv',  label: 'CSV Spreadsheet',  icon: 'CSV', ext: '.csv',  mime: 'text/csv' },
    { id: 'tsv',  label: 'TSV Spreadsheet',  icon: 'TSV', ext: '.tsv',  mime: 'text/tab-separated-values' },
    { id: 'yaml', label: 'YAML',             icon: '~',  ext: '.yaml', mime: 'text/yaml' },
    { id: 'tex',  label: 'LaTeX Source',     icon: 'Λ',  ext: '.tex',  mime: 'application/x-latex' },
    { id: 'epub', label: 'EPUB eBook',       icon: 'EPB', ext: '.epub', mime: 'application/epub+zip' },
    { id: 'odt',  label: 'OpenDocument',     icon: 'ODT', ext: '.odt',  mime: 'application/vnd.oasis.opendocument.text' },
];

// --- Content to string helpers ---

function sectionToText(s: ExportSection): string {
    const content = typeof s.content === 'string'
        ? s.content
        : Array.isArray(s.content)
        ? s.content.join('\n')
        : JSON.stringify(s.content, null, 2);
    return `${s.heading.toUpperCase()}\n${'─'.repeat(s.heading.length)}\n${content}`;
}

function buildTxt(d: ExportData): string {
    const lines = [`POLI DOSSIER: ${d.title}`, `Type: ${d.type}`, d.subtitle || '', d.date ? `Date: ${d.date}` : '', '═'.repeat(60), ''];
    (d.sections || []).forEach(s => { lines.push(sectionToText(s), ''); });
    if (d.rawData) lines.push('RAW DATA\n' + '─'.repeat(8), JSON.stringify(d.rawData, null, 2));
    lines.push('', `Generated by POLI — ${new Date().toISOString()}`);
    return lines.join('\n');
}

function buildHtml(d: ExportData): string {
    const sections = (d.sections || []).map(s => {
        const content = typeof s.content === 'string'
            ? `<p>${s.content.replace(/\n/g, '<br>')}</p>`
            : Array.isArray(s.content)
            ? `<ul>${s.content.map(i => `<li>${i}</li>`).join('')}</ul>`
            : `<pre>${JSON.stringify(s.content, null, 2)}</pre>`;
        return `<section><h2>${s.heading}</h2>${content}</section>`;
    }).join('\n');
    return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">
<title>${d.title} — POLI</title>
<style>
  body{font-family:Georgia,serif;max-width:860px;margin:40px auto;padding:0 20px;line-height:1.7;color:#1a1a1a}
  h1{font-size:2em;border-bottom:3px solid #8b0000;padding-bottom:.3em}
  h2{font-size:1.3em;margin-top:2em;color:#4a0000;border-bottom:1px solid #ddd;padding-bottom:.2em}
  .meta{color:#666;font-size:.9em;margin-bottom:2em}
  ul{padding-left:1.5em}
  pre{background:#f5f5f5;padding:1em;border-radius:4px;overflow:auto;font-size:.85em}
  footer{margin-top:3em;padding-top:1em;border-top:1px solid #ddd;color:#888;font-size:.8em}
</style></head><body>
<h1>${d.title}</h1>
<div class="meta"><strong>${d.type}</strong>${d.subtitle ? ` — ${d.subtitle}` : ''}${d.date ? ` | ${d.date}` : ''}</div>
${sections}
<footer>Generated by POLI on ${new Date().toLocaleDateString()}</footer>
</body></html>`;
}

function buildMarkdown(d: ExportData): string {
    const lines = [`# ${d.title}`, `**${d.type}**${d.subtitle ? ` — ${d.subtitle}` : ''}${d.date ? ` | ${d.date}` : ''}`, ''];
    (d.sections || []).forEach(s => {
        lines.push(`## ${s.heading}`, '');
        if (typeof s.content === 'string') lines.push(s.content, '');
        else if (Array.isArray(s.content)) { s.content.forEach(i => lines.push(`- ${i}`)); lines.push(''); }
        else lines.push('```json', JSON.stringify(s.content, null, 2), '```', '');
    });
    lines.push('---', `*Generated by POLI — ${new Date().toISOString()}*`);
    return lines.join('\n');
}

function buildJson(d: ExportData): string {
    return JSON.stringify({ title: d.title, type: d.type, subtitle: d.subtitle, date: d.date, sections: d.sections, rawData: d.rawData, generatedAt: new Date().toISOString() }, null, 2);
}

function toXmlValue(v: any, indent = 2): string {
    if (v === null || v === undefined) return '';
    if (typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean')
        return String(v).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
    if (Array.isArray(v)) return v.map((i, idx) => `${' '.repeat(indent)}<item index="${idx}">${toXmlValue(i, indent + 2)}</item>`).join('\n');
    return Object.entries(v).map(([k, val]) => `${' '.repeat(indent)}<${k}>${toXmlValue(val, indent + 2)}</${k}>`).join('\n');
}

function buildXml(d: ExportData): string {
    const sections = (d.sections || []).map(s =>
        `  <section>\n    <heading>${s.heading}</heading>\n    <content>${toXmlValue(s.content, 4)}</content>\n  </section>`
    ).join('\n');
    return `<?xml version="1.0" encoding="UTF-8"?>\n<poliDossier>\n  <title>${d.title}</title>\n  <type>${d.type}</type>\n  <subtitle>${d.subtitle || ''}</subtitle>\n  <date>${d.date || ''}</date>\n  <sections>\n${sections}\n  </sections>\n  <generatedAt>${new Date().toISOString()}</generatedAt>\n</poliDossier>`;
}

function buildCsv(d: ExportData, sep = ','): string {
    const q = (s: string) => `"${String(s).replace(/"/g, '""')}"`;
    const rows: string[][] = [['Section', 'Content']];
    rows.push(['Title', d.title], ['Type', d.type]);
    if (d.subtitle) rows.push(['Subtitle', d.subtitle]);
    (d.sections || []).forEach(s => {
        const content = typeof s.content === 'string' ? s.content
            : Array.isArray(s.content) ? s.content.join('; ')
            : JSON.stringify(s.content);
        rows.push([s.heading, content]);
    });
    return rows.map(r => r.map(c => q(c)).join(sep)).join('\n');
}

function buildRtf(d: ExportData): string {
    const esc = (s: string) => s.replace(/\\/g, '\\\\').replace(/\{/g, '\\{').replace(/\}/g, '\\}').replace(/[^\x00-\x7F]/g, c => `\\u${c.charCodeAt(0)}?`);
    let body = `{\\b\\fs36 ${esc(d.title)}}\\par\\par{\\i ${esc(d.type)}${d.subtitle ? ` — ${esc(d.subtitle)}` : ''}}\\par\\par`;
    (d.sections || []).forEach(s => {
        body += `{\\b\\fs26 ${esc(s.heading)}}\\par`;
        const text = typeof s.content === 'string' ? s.content : Array.isArray(s.content) ? s.content.join('\n') : JSON.stringify(s.content);
        body += `${esc(text)}\\par\\par`;
    });
    return `{\\rtf1\\ansi\\deff0{\\fonttbl{\\f0 Times New Roman;}}\\f0\\fs24 ${body}}`;
}

function buildDoc(d: ExportData): string {
    // HTML with Word-compatible DOCTYPE — opens in MS Word
    return `<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word'>
<head><meta charset='utf-8'><title>${d.title}</title>
<style>body{font-family:Calibri,sans-serif;font-size:12pt;line-height:1.5}h1{font-size:24pt;color:#7B0000}h2{font-size:16pt;color:#3D0000;border-bottom:1px solid #aaa}p{margin:.5em 0}</style>
</head><body>
<h1>${d.title}</h1><p><strong>${d.type}</strong>${d.subtitle ? ` — ${d.subtitle}` : ''}</p><hr>
${(d.sections || []).map(s => {
    const content = typeof s.content === 'string' ? `<p>${s.content.replace(/\n/g, '</p><p>')}</p>`
        : Array.isArray(s.content) ? `<ul>${s.content.map(i => `<li>${i}</li>`).join('')}</ul>`
        : `<pre>${JSON.stringify(s.content, null, 2)}</pre>`;
    return `<h2>${s.heading}</h2>${content}`;
}).join('\n')}
<p><em>Generated by POLI — ${new Date().toLocaleDateString()}</em></p>
</body></html>`;
}

function buildYaml(d: ExportData): string {
    const esc = (s: any): string => {
        const str = String(s ?? '');
        return str.includes(':') || str.includes('\n') || str.includes('"') ? `"${str.replace(/"/g, '\\"')}"` : str;
    };
    const lines = [`title: ${esc(d.title)}`, `type: ${esc(d.type)}`, `subtitle: ${esc(d.subtitle || '')}`, `date: ${esc(d.date || '')}`, `generatedAt: ${new Date().toISOString()}`, `sections:`];
    (d.sections || []).forEach(s => {
        lines.push(`  - heading: ${esc(s.heading)}`);
        if (typeof s.content === 'string') lines.push(`    content: ${esc(s.content)}`);
        else if (Array.isArray(s.content)) { lines.push('    content:'); s.content.forEach(i => lines.push(`      - ${esc(i)}`)); }
        else lines.push(`    content: ${esc(JSON.stringify(s.content))}`);
    });
    return lines.join('\n');
}

function buildLatex(d: ExportData): string {
    const esc = (s: string) => s.replace(/[&%$#_{}~^\\]/g, m => `\\${m}`);
    const sections = (d.sections || []).map(s => {
        const content = typeof s.content === 'string' ? esc(s.content)
            : Array.isArray(s.content) ? `\\begin{itemize}\n${s.content.map(i => `  \\item ${esc(i)}`).join('\n')}\n\\end{itemize}`
            : `\\begin{verbatim}${JSON.stringify(s.content, null, 2)}\\end{verbatim}`;
        return `\\section{${esc(s.heading)}}\n${content}`;
    }).join('\n\n');
    return `\\documentclass[12pt]{article}
\\usepackage[utf8]{inputenc}
\\usepackage[T1]{fontenc}
\\usepackage{geometry}
\\geometry{margin=1in}
\\title{${esc(d.title)}}
\\author{POLI}
\\date{${new Date().toLocaleDateString()}}
\\begin{document}
\\maketitle
${d.subtitle ? `\\textit{${esc(d.subtitle)}}\\\\[1em]` : ''}
${sections}
\\end{document}`;
}

function buildEpub(d: ExportData): string {
    // Return EPUB as XHTML (browsers and e-readers can open; proper EPUB requires zip)
    const sections = (d.sections || []).map(s => {
        const content = typeof s.content === 'string' ? `<p>${s.content.replace(/\n/g, '</p><p>')}</p>`
            : Array.isArray(s.content) ? `<ul>${s.content.map(i => `<li>${i}</li>`).join('')}</ul>`
            : `<pre>${JSON.stringify(s.content, null, 2)}</pre>`;
        return `<section epub:type="chapter"><h2>${s.heading}</h2>${content}</section>`;
    }).join('\n');
    return `<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
<head><meta charset="utf-8"/><title>${d.title}</title>
<style>body{font-family:serif;line-height:1.6;max-width:600px;margin:auto;padding:1em}h1{font-size:2em}h2{font-size:1.3em;margin-top:2em}section{margin-bottom:2em}</style>
</head><body>
<h1>${d.title}</h1>
<p><strong>${d.type}</strong>${d.subtitle ? ` — ${d.subtitle}` : ''}</p>
${sections}
<footer><small>Generated by POLI — ${new Date().toISOString()}</small></footer>
</body></html>`;
}

function buildOdt(d: ExportData): string {
    // Minimal ODF content.xml wrapped in flat ODF XML (opens in LibreOffice)
    const paras = (d.sections || []).map(s => {
        const esc = (str: string) => str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
        const content = typeof s.content === 'string' ? s.content : Array.isArray(s.content) ? s.content.join('\n') : JSON.stringify(s.content);
        return `<text:h text:style-name="Heading_2" text:outline-level="2">${esc(s.heading)}</text:h><text:p text:style-name="Text_Body">${esc(content)}</text:p>`;
    }).join('');
    return `<?xml version="1.0" encoding="UTF-8"?>
<office:document xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0"
  xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0"
  office:mimetype="application/vnd.oasis.opendocument.text">
<office:body><office:text>
<text:h text:outline-level="1">${d.title}</text:h>
<text:p text:style-name="Text_Body">${d.type}${d.subtitle ? ` — ${d.subtitle}` : ''}</text:p>
${paras}
</office:text></office:body></office:document>`;
}

// --- Download trigger ---

function triggerDownload(content: string, filename: string, mime: string) {
    const blob = new Blob([content], { type: `${mime};charset=utf-8` });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    setTimeout(() => { document.body.removeChild(a); URL.revokeObjectURL(url); }, 100);
}

// --- Main export function ---

export function exportAs(data: ExportData, format: ExportFormat): void {
    const safe = data.title.replace(/[^a-z0-9]/gi, '_').toLowerCase();
    const meta = EXPORT_FORMATS.find(f => f.id === format)!;

    if (format === 'pdf') {
        // Open a print-optimised HTML page in a new tab → user saves as PDF
        const html = buildHtml(data);
        const w = window.open('', '_blank');
        if (w) { w.document.write(html); w.document.close(); w.print(); }
        return;
    }

    let content: string;
    switch (format) {
        case 'txt':   content = buildTxt(data); break;
        case 'html':  content = buildHtml(data); break;
        case 'md':    content = buildMarkdown(data); break;
        case 'json':  content = buildJson(data); break;
        case 'xml':   content = buildXml(data); break;
        case 'csv':   content = buildCsv(data, ','); break;
        case 'tsv':   content = buildCsv(data, '\t'); break;
        case 'rtf':   content = buildRtf(data); break;
        case 'doc':   content = buildDoc(data); break;
        case 'yaml':  content = buildYaml(data); break;
        case 'tex':   content = buildLatex(data); break;
        case 'epub':  content = buildEpub(data); break;
        case 'odt':   content = buildOdt(data); break;
        default:      content = buildTxt(data);
    }

    triggerDownload(content, `${safe}${meta.ext}`, meta.mime);
}

/** Convenience: build ExportData from a simple title + plain text content */
export function simpleExportData(title: string, type: string, content: string, subtitle?: string): ExportData {
    const paragraphs = content.split(/\n{2,}/);
    return {
        title,
        type,
        subtitle,
        date: new Date().toLocaleDateString(),
        sections: [{ heading: 'Content', content: paragraphs.join('\n\n') }],
    };
}
